### ISSUE TITLE
ovirt-common - just for adding repos? Why not use yum repository module?

### ISSUE THREAD

**Issue by mykaul** [rhevm-qe-automation/ovirt-ansible#142]
What's the point of a role that only adds repos? Why not use http://docs.ansible.com/ansible/latest/yum_repository_module.html ?

**Comment by mykaul** [comment]
@pkubica  ?

**Comment by pkubica** [comment]
In role ovirt-common we are adding repositories in multiple ways. One of them is creating repositories from parameters like baseurl, description... on that we are using yum_repository module, but the other ways, how to add repository to system, are by rpm package or download specific .repo files and on that you can't use yum_repository module.
Second part is about libselinux-python package. In role ovirt-common we are installing that package due to selinux policy and Ansible.

**Comment by KKoukiou** [comment]
ovirt-common role was replaced by https://github.com/oVirt/ovirt-ansible-repositories, which is actually just a duplicate of this role moved to oVirt organization.
https://github.com/rhevm-qe-automation/ovirt-ansible/pull/166 will totally remove ovirt-common.
@pkubica  JFYI the ownership of the new role is still on you, https://github.com/oVirt/ovirt-ansible-repositories/blob/master/meta/main.yml
